import requests

# Query events by category
lowest_category = 101
highest_category = 120
number_per_category = 150

# URL which return JSON string
base_url = 'https://www.eventbriteapi.com/v3/events/search/?token=YQVEX6PF66QPHON2KHD3'

number_of_pages = number_per_category/50 + 1
print('number of pages: ' + str(number_of_pages))

# Each request only returns 50 results, so do it multiple times
current_page = 1
while current_page <= number_of_pages:
    print('current page: ' + str(current_page))

    current_category_id = lowest_category
    while current_category_id <= highest_category:
        print('current category id: ' + str(current_category_id))

        url = base_url + '&sort_by=date&categories=' + str(current_category_id) + '&page=' + str(current_page)

        # Get list of events
        request_string = requests.get(url)
        request_array = request_string.json()
        events = request_array['events']

        # Iterate through events
        last_description = ''
        for item in events:
            description = item['description']['text']
            if description:

                # Replace \n, \r, weird space, -, and leading and trailing spaces
                description = description.replace('\n', ' ')
                description = description.replace('\r', ' ')
                description = description.replace(' ', ' ')  # weird character that exists in descriptions that is not a space
                description = description.replace('-', ' ')
                description = description.strip()

                # Get rid of double spaces generated by all the replacing
                old_string = ''
                while description != old_string:
                    old_string = description
                    description = description.replace('  ', ' ')

                # Check for duplicates
                if description != last_description:
                    last_description = description

                    # Add event description to relevant .txt file, separate descriptions with \n
                    filename = 'categories/' + str(current_category_id) + '.txt'

                    file = open(filename, 'a')
                    file.write(description)
                    file.write('\n')
                    file.close()

        current_category_id += 1
    current_page += 1
